#!/usr/bin/env python3
"""One onboarding page per family, generated from what is true on this disk.

    uv run qm cookbook --write walkthrough/families
    uv run qm cookbook --check walkthrough/families

**GENERATED, BECAUSE A HAND-WRITTEN ONBOARDING PAGE GOES STALE FIRST.** It is
read by exactly the person least able to notice it is wrong -- somebody new,
who has no way to tell a stale instruction from a current one. So every figure
here comes from `families.json` and from the clones on this disk, and the page
is regenerated by the ordinary command rather than edited.

**THE PICTURE IS DRAWN, NOT PASTED.** Each page carries an SVG of its family,
emitted here from the same data as the prose beside it. A screenshot pasted
into a document is a claim about a moment nobody can re-take;
`records/DRAFT-one-executable-walkthrough.md` is the decision, and this is that
rule applied to a diagram.

WHAT THESE PAGES CANNOT DO. Tell a reader whether a repository works. They
report what the org has claimed and what the disk shows -- a family, its
members, which carry governance, and which have uncommitted work. Three of the
four families have no adopted member, so their pages are honest about having
no governed entry point rather than inventing one.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FAMILIES = ROOT / "families.json"
SEARCH_ROOTS = (ROOT.parent, ROOT.parent.parent)


def git(path: Path, *args: str) -> str:
    try:
        done = subprocess.run(["git", "-C", str(path), *args], capture_output=True,
                              encoding="utf-8", errors="replace", timeout=30)
    except (OSError, subprocess.TimeoutExpired):
        return ""
    return done.stdout.strip() if done.returncode == 0 else ""


def clone_of(name: str) -> Path | None:
    for root in SEARCH_ROOTS:
        candidate = root / name
        if (candidate / ".git").exists():
            return candidate
    return None


def member_state(name: str, adopted: set[str]) -> dict:
    """What the disk says about one member. Never a default that reads as good."""
    clone = clone_of(name)
    if clone is None:
        return {"name": name, "on_disk": False, "branch": "-", "dirty": None,
                "last": "-", "adopted": name in adopted}
    dirty = [line for line in git(clone, "status", "--porcelain=v1").splitlines() if line]
    return {
        "name": name,
        "on_disk": True,
        "branch": git(clone, "rev-parse", "--abbrev-ref", "HEAD") or "?",
        "dirty": len(dirty),
        "last": git(clone, "log", "-1", "--format=%cs") or "?",
        "adopted": name in adopted,
    }


def adopted_names() -> set[str]:
    """Repositories governance reaches, which is not only the adopting ones.

    A `project/<name>` branch is how a *project* carries records. The corpus
    itself has none and is not thereby ungoverned -- it is the thing doing the
    governing, and the roster says so with `role: corpus`. Reading only the
    branches printed the corpus as the one member of its own family without
    governance, and sent a newcomer to the second-listed repository instead.
    """
    out = git(ROOT, "for-each-ref", "--format=%(refname:short)",
              "refs/remotes/origin/project")
    names = {line.split("/", 2)[-1] for line in out.splitlines() if line}
    sys.path.insert(0, str(ROOT / "ci"))
    try:
        import roster
        names |= {e.get("name") for e in roster.load()
                  if e.get("role") == "corpus" and e.get("name")}
    except Exception:
        pass
    return names


def svg(family: str, members: list[dict]) -> str:
    """The family as a picture, drawn from the same data as the prose.

    Deliberately plain: no gradients, no font that has to be present, and a
    palette that survives both themes. A diagram nobody can re-generate is the
    thing this file exists to avoid, so it is small enough to read as text.
    """
    row, pad = 26, 14
    width, height = 560, pad * 2 + 30 + row * len(members)
    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}" role="img" '
        f'aria-label="the {family} family and its members">',
        f'<rect width="{width}" height="{height}" fill="none"/>',
        f'<text x="{pad}" y="{pad + 14}" font-family="monospace" font-size="14" '
        f'font-weight="bold" fill="currentColor">{family}</text>',
    ]
    for index, member in enumerate(members):
        y = pad + 34 + index * row
        mark = "*" if member["adopted"] else "."
        state = "governed" if member["adopted"] else "not adopted"
        parts.append(
            f'<text x="{pad}" y="{y}" font-family="monospace" font-size="12" '
            f'fill="currentColor">{mark} {member["name"]}</text>'
        )
        parts.append(
            f'<text x="{pad + 230}" y="{y}" font-family="monospace" font-size="12" '
            f'fill="currentColor" opacity="0.7">{state}</text>'
        )
    parts.append(
        f'<text x="{pad}" y="{height - 4}" font-family="monospace" font-size="10" '
        f'fill="currentColor" opacity="0.6">'
        f'* governed  . not adopted</text>')
    parts.append("</svg>")
    return "\n".join(parts) + "\n"


def page(family: dict, states: list[dict], generated_at: str) -> str:
    name = family["name"]
    adopted = [s for s in states if s["adopted"]]
    absent = [s for s in states if not s["on_disk"]]
    dirty = [s for s in states if s["on_disk"] and s["dirty"]]
    lines = [
        f"# Cookbook — the `{name}` family",
        "",
        "**This page is generated.** Every figure comes from `families.json` and "
        "from the clones on this disk, and `uv run qm cookbook --check` fails the "
        "build when it stops being true. Do not edit it; edit the roster or the "
        "record and regenerate.",
        "",
        f"**Drives** {family['drives']}",
        "",
        f"![the {name} family](./{name}.svg)",
        "",
        "## Who is in it",
        "",
        "| member | governed |",
        "|---|---|",
    ]
    for state in states:
        lines.append(
            f"| `{state['name']}` | {'yes' if state['adopted'] else 'no'} |")
    lines += [
        "",
        "## Starting here",
        "",
    ]
    if adopted:
        # The corpus first when it is in this family: it is where the rules are,
        # and a newcomer sent anywhere else reads a consumer before the contract.
        first = next((s["name"] for s in adopted if s["name"] == "qm"),
                     adopted[0]["name"])
        lines += [
            f"{len(adopted)} of {len(states)} members carry governance, so this "
            f"family has a governed entry point. Begin in `{first}`:",
            "",
            "```sh",
            f"cd {first}",
            "uv run qm cowork          # or read AGENTS.md, if this repo has no CLI",
            "```",
            "",
            "A governed member is one with a `project/<name>` branch in the corpus. "
            "Its records live there, not in the repository itself.",
        ]
    else:
        lines += [
            "**No member of this family carries governance yet**, so there is no "
            "governed entry point and this page will not invent one. Reading the "
            "code is the entry point.",
            "",
            "Adopting one is `handbook/forking-a-project.md` — nine steps, taken one "
            "repository at a time, and a decision per repository rather than per "
            "family. Nothing here recommends which; that is the border test in "
            "`records/DRAFT-a-family-is-bordered-by-what-it-drives.md` §2 applied by "
            "somebody who knows what the code does.",
        ]
    lines += [
        "",
        "## What this page deliberately does not carry",
        "",
        "**Anything machine-scoped.** Which branch a clone is on, how many "
        "uncommitted files it has, whether it is on this disk at all — none of "
        "that is here, because this page is committed and those facts differ per "
        "machine and per keystroke. A committed document carrying them drifts "
        "every time somebody edits a file, and a check that fails hourly is one "
        "people learn to rerun rather than read.",
        "",
        "`ci/workspace.yaml` and `inventory-public.json` make the same split for "
        "the same reason, with the machine-scoped half in an uncommitted "
        "companion. Run `uv run qm cookbook` with no argument to see this "
        "family's state on the disk you are actually sitting at.",
        "",
        "## What this page cannot tell you",
        "",
        "Whether any of it works. It reports a claim — the family, stated by a "
        "person in the roster — and it does not run a member. A family name is "
        "never a statement that anybody is working on it.",
        "",
        f"*Generated {generated_at} from `families.json`.*",
        "",
    ]
    return "\n".join(lines)


def build(out: Path) -> dict[str, str]:
    document = json.loads(FAMILIES.read_text(encoding="utf-8"))
    adopted = adopted_names()
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    files: dict[str, str] = {}
    index = [
        "# Cookbook — the families",
        "",
        "One page per family, generated from `families.json` and the clones on this "
        "disk. The families themselves are decided in "
        "`records/DRAFT-a-family-is-bordered-by-what-it-drives.md`; this is the "
        "onboarding view of them.",
        "",
        "| family | drives | members | governed |",
        "|---|---|---|---|",
    ]
    for family in document["families"]:
        states = [member_state(name, adopted) for name in family["members"]]
        files[f"{family['name']}.md"] = page(family, states, stamp)
        files[f"{family['name']}.svg"] = svg(family["name"], states)
        governed = sum(1 for s in states if s["adopted"])
        index.append(
            f"| [`{family['name']}`](./{family['name']}.md) | {family['drives']} | "
            f"{len(states)} | {governed} |")
    index += [
        "",
        f"`{len(document['unstated'])}` rostered repositories claim no family. That "
        "is *unstated*, not *none* — nobody has answered the question for them, and "
        "a page that listed them as unfamilied would be inventing an answer.",
        "",
        f"*Generated {stamp}.*",
        "",
    ]
    files["README.md"] = "\n".join(index)
    return files


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("out", nargs="?", default="walkthrough/families")
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    out = Path(args.out)
    files = build(out)

    if args.check:
        stale = []
        for name, body in files.items():
            path = out / name
            if not path.is_file():
                stale.append(f"{path}: missing")
            elif _without_stamp(path.read_text(encoding="utf-8")) != _without_stamp(body):
                stale.append(f"{path}: out of date")
        for problem in stale:
            print(f"  {problem}", file=sys.stderr)
        if stale:
            print(f"\ncookbook: {len(stale)} page(s) no longer describe this disk. "
                  f"Regenerate with `uv run qm cookbook --write`.", file=sys.stderr)
            return 1
        print(f"cookbook: {len(files)} page(s) still describe this disk.")
        return 0

    if args.write:
        out.mkdir(parents=True, exist_ok=True)
        for name, body in files.items():
            (out / name).write_text(body, encoding="utf-8")
        print(f"wrote {len(files)} file(s) to {out}")
        return 0

    # No flag: the machine-scoped view. This is the half the committed pages
    # deliberately omit -- it differs per machine and per keystroke, so it is
    # printed and never written, exactly as `inventory-local.json` is kept out
    # of the public inventory.
    document = json.loads(FAMILIES.read_text(encoding="utf-8"))
    adopted = adopted_names()
    print("This disk, right now. None of it is committed anywhere.")
    print()
    for family in document["families"]:
        states = [member_state(name, adopted) for name in family["members"]]
        absent = [s for s in states if not s["on_disk"]]
        dirty = [s for s in states if s["on_disk"] and s["dirty"]]
        print(f"## {family['name']}")
        for state in states:
            where = ("not on this disk" if not state["on_disk"]
                     else f"{state['branch']:34} {state['dirty']:>3} dirty  {state['last']}")
            print(f"   {'*' if state['adopted'] else ' '} {state['name']:20} {where}")
        notes = []
        if absent:
            notes.append(f"{len(absent)} not on this disk")
        if dirty:
            worst = max(dirty, key=lambda s: s["dirty"])
            notes.append(f"{len(dirty)} with uncommitted work, most in {worst['name']}"
                         f" ({worst['dirty']}) -- it lives in no ref")
        summary = "; ".join(notes) if notes else "every member present, every tree clean"
        print(f"     {summary}")
        print()
    print("`* ` is governed. Read the committed pages for what the org claims; "
          "this is only what is here.")
    return 0


def _without_stamp(text: str) -> str:
    """Compare content, not the date it was generated.

    The stamp moves every day and nothing else does, so comparing it would make
    the check fail daily for no reason -- a check that cries wolf is one people
    learn to rerun rather than read.
    """
    return "\n".join(line for line in text.splitlines()
                     if not line.startswith("*Generated "))


if __name__ == "__main__":
    raise SystemExit(main())
