#!/usr/bin/env python3
"""Render the disk status document as one self-contained HTML page, or as prose.

Org-level tooling, copied nowhere. It reads a document and writes a view. That
is the whole contract, and it is the same contract ci/harness_dashboard.py and
ci/governance_render.py have.

WHAT THIS MAY NOT DO, and why the list matters more than the features:

  - It may not stat a file, walk a directory, or ask the operating system how
    much space is left. If a fact is not in the document, this renderer does not
    have it, and the fix is a change to ci/disk_status.py where the measurement
    is defined once. A convenience call to shutil.disk_usage here would be a
    second definition of "free", and the two would disagree the first time
    somebody rendered an old document.
  - It may not delete anything, or print a command that deletes something
    without saying it is a dry run by default.
  - It may not present a stale document as current. A disk figure ages faster
    than any other fact this org generates -- one container pull moves it by
    gigabytes -- so `generated_at` is rendered at the top, with its age, and the
    page says outright when the budget has passed.
  - It may not render an unmeasured target as an empty one. A cache behind a
    permission error must not look like a cache with nothing in it, because the
    first is an absence of evidence and the second reads as nothing to do.

Usage:
    python ci/disk_dashboard.py disk-status.json --out disk.html
    python ci/disk_dashboard.py disk-status.json --format md
"""

from __future__ import annotations

import argparse
import html
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

from dashboard_style import STYLE

OK, WARN, UNKNOWN = "ok", "warn", "unknown"

LINE_BREAK = chr(10)

# What each safety tier costs the reader, in the words the page uses. Kept here
# rather than in the document because it is a property of the tier and not of
# any one machine's measurement -- and kept out of the generator so that a
# rewording is not a reason to regenerate.
TIER_MEANING = {
    "refetched": "downloaded again automatically, next time the tool needs it",
    "rebuilt": "regenerated by a command you run — an install, a build, a download",
    "destructive": "nothing comes back",
}


def esc(value: object) -> str:
    return html.escape("" if value is None else str(value))


def unknown_reason(value: object) -> str | None:
    """The reason, if this value is the document's unknown form."""
    if isinstance(value, dict) and "unknown" in value and len(value) == 1:
        return str(value["unknown"])
    return None


def pill(text: str, state: str) -> str:
    return f'<span class="pill p-{state}">{esc(text)}</span>'


def size(count: object) -> str:
    """Bytes at a scale a person reads, never rounded to nothing.

    A 40MB cache rendered as `0.0GB` reads as empty, which is the same failure
    as rendering an unknown as a zero: the number is not wrong and the reader
    still draws the wrong conclusion.
    """
    if not isinstance(count, (int, float)):
        return "unknown"
    if count >= 10**9:
        return f"{count / 10**9:.1f} GB"
    if count >= 10**6:
        return f"{count / 10**6:.0f} MB"
    if count >= 10**3:
        return f"{count / 10**3:.0f} KB"
    return f"{int(count)} B"


def age_hours(stamp: object) -> float | None:
    if not isinstance(stamp, str):
        return None
    try:
        moment = datetime.fromisoformat(stamp.strip().replace("Z", "+00:00"))
    except ValueError:
        return None
    if moment.tzinfo is None:
        moment = moment.replace(tzinfo=timezone.utc)
    return (datetime.now(timezone.utc) - moment).total_seconds() / 3600


def age_text(hours: float | None) -> str:
    if hours is None:
        return "age unknown"
    if hours < 1:
        return f"{hours * 60:.0f} minutes old"
    if hours < 48:
        return f"{hours:.0f} hours old"
    return f"{hours / 24:.0f} days old"


def staleness(document: dict) -> tuple[str, str]:
    """(text, state) for the document's own age.

    A disk dashboard that looks live and is a day old is worse than one that
    admits it, because the first stops people checking and the second is why
    they check. So the age is rendered beside the timestamp, not computed by a
    reader from a string they have to parse.
    """
    budget = (document.get("reading") or {}).get("staleness_budget_hours")
    hours = age_hours(document.get("generated_at"))
    if hours is None:
        return "age unknown — the timestamp could not be read", UNKNOWN
    if isinstance(budget, (int, float)) and hours > budget:
        return f"{age_text(hours)} — past the {budget:g}h budget, re-measure before acting", WARN
    return age_text(hours), OK


def volume_row(volume: dict) -> str:
    reason = unknown_reason(volume.get("usage"))
    if reason is not None:
        return (
            f'<tr class="unmeasured"><th scope="row">{esc(volume.get("path"))}</th>'
            f'<td class="s-unknown" colspan="4" title="{esc(reason)}">'
            f"unknown — {esc(reason)}</td></tr>"
        )

    severity = volume.get("severity", UNKNOWN)
    state = OK if severity == "ok" else WARN if severity in ("warn", "critical") else UNKNOWN
    label = {"ok": "ok", "warn": "low", "critical": "critical"}.get(severity, "unknown")
    fired = volume.get("thresholds_fired") or []
    ratio = volume.get("free_ratio")
    return (
        f'<tr class="{"over" if state == WARN else ""}">'
        f'<th scope="row">{esc(volume.get("path"))}</th>'
        f"<td>{esc(size(volume.get('total_bytes')))}</td>"
        f"<td>{esc(size(volume.get('used_bytes')))}</td>"
        f"<td><b>{esc(size(volume.get('free_bytes')))}</b>"
        + (f'<div class="sub">{ratio:.1%}</div>' if isinstance(ratio, float) else "")
        + f"</td><td>{pill(label, state)}"
        + (f'<div class="sub">{esc("; ".join(fired))}</div>' if fired else "")
        + "</td></tr>"
    )


def target_row(target: dict) -> str:
    measured = target.get("measured") or {}
    reason = unknown_reason(measured)
    safety = str(target.get("safety", UNKNOWN))
    tier_cell = (
        f"<td>{esc(safety)}"
        f'<div class="sub">{esc(TIER_MEANING.get(safety, "unclassified"))}</div></td>'
    )

    if reason is not None:
        return (
            f'<tr class="unmeasured"><th scope="row">{esc(target.get("title"))}'
            f'<div class="sub mono">{esc(target.get("name"))}</div></th>'
            + tier_cell
            + f'<td class="s-unknown" colspan="2" title="{esc(reason)}">'
            f"unknown — {esc(reason)}</td></tr>"
        )

    units = measured.get("units") or []
    total_units = measured.get("units_total", len(units))
    detail = "".join(
        f'<div class="sub mono">{esc(size(u.get("bytes")))} · {esc(u.get("path"))}</div>'
        for u in units
    )
    if total_units > len(units):
        detail += f'<div class="sub">and {total_units - len(units)} more</div>'
    if not units and measured.get("note"):
        detail = f'<div class="sub">{esc(measured["note"])}</div>'

    unreadable = measured.get("unreadable") or 0
    floor = (
        f'<div class="sub s-unknown">{unreadable} paths unreadable — '
        "this figure is a floor</div>"
        if unreadable
        else ""
    )
    return (
        "<tr>"
        f'<th scope="row">{esc(target.get("title"))}'
        f'<div class="sub mono">{esc(target.get("name"))}</div></th>'
        + tier_cell
        + f"<td><b>{esc(size(measured.get('bytes')))}</b>{floor}</td>"
        + f"<td>{detail}</td></tr>"
    )


def render(document: dict, fragment: bool = False) -> str:
    generator = document.get("generator", {})
    totals = document.get("totals", {})
    volumes = document.get("volumes", [])
    targets = document.get("targets", [])
    reclaimable = totals.get("reclaimable_bytes") or {}

    stale_text, stale_state = staleness(document)

    pressed = [
        v for v in volumes
        if unknown_reason(v.get("usage")) is None and v.get("severity") in ("warn", "critical")
    ]
    unmeasured = [t for t in targets if unknown_reason(t.get("measured")) is not None]

    # Sorted by what it frees, and only the tier that costs nothing. The page
    # answers "what do I run right now", and a list led by a 40GB target that
    # needs a rebuild is a list that gets read past.
    cheap = sorted(
        (
            t for t in targets
            if t.get("safety") == "refetched"
            and unknown_reason(t.get("measured")) is None
            and (t["measured"].get("bytes") or 0) > 0
        ),
        key=lambda t: -(t["measured"].get("bytes") or 0),
    )

    plan_html = (
        "".join(
            f'<div class="gap"><h3>{esc(t["title"])}</h3>'
            f"<p>{esc(size(t['measured']['bytes']))} — "
            f"{esc(TIER_MEANING.get(str(t.get('safety')), 'unclassified'))}."
            + (f" {esc(t['why'])}" if t.get("why") else "")
            + "</p></div>"
            for t in cheap
        )
        or '<p class="s-ok">Nothing in the cheapest tier holds measurable space.</p>'
    )

    pressed_html = (
        "".join(
            f'<div class="gap"><h3>{esc(v["path"])}</h3>'
            f"<p>{esc(size(v.get('free_bytes')))} free of "
            f"{esc(size(v.get('total_bytes')))}. "
            f"{esc('; '.join(v.get('thresholds_fired') or []))}.</p></div>"
            for v in pressed
        )
        or '<p class="s-ok">Every volume measured is above both thresholds.</p>'
    )

    unmeasured_html = (
        "".join(
            f'<p><b>{esc(t["name"])}</b> — {esc(unknown_reason(t["measured"]))}</p>'
            for t in unmeasured
        )
        or "<p>Every target in the policy was measured.</p>"
    )

    return (FRAGMENT if fragment else TEMPLATE).format(
        style=STYLE,
        generated_at=esc(document.get("generated_at")),
        age=esc(stale_text),
        age_state=esc(stale_state),
        policy=esc(generator.get("policy")),
        scope=esc(generator.get("scope")),
        n_volumes=esc(totals.get("volumes")),
        n_critical=esc(totals.get("volumes_critical")),
        n_warn=esc(totals.get("volumes_warn")),
        n_targets=esc(totals.get("targets")),
        n_unknown=esc(totals.get("targets_unknown")),
        free_refetched=esc(size(reclaimable.get("refetched"))),
        free_rebuilt=esc(size(reclaimable.get("rebuilt"))),
        free_destructive=esc(size(reclaimable.get("destructive"))),
        volumes=LINE_BREAK.join(volume_row(v) for v in volumes)
        or '<tr><td colspan="5" class="s-unknown">No volume was measured.</td></tr>',
        targets=LINE_BREAK.join(
            target_row(t)
            for t in sorted(
                targets,
                key=lambda t: -((t.get("measured") or {}).get("bytes") or 0),
            )
        )
        or '<tr><td colspan="4" class="s-unknown">The policy names no targets.</td></tr>',
        plan=plan_html,
        pressed=pressed_html,
        unmeasured=unmeasured_html,
        remediate=esc((document.get("reading") or {}).get("remediate", "")),
        refresh=esc((document.get("reading") or {}).get("refresh", "")),
    )


BODY = """<main>
<h1>Disk status</h1>
<div class="stamp">
  <span>generated <b>{generated_at}</b></span>
  <span class="s-{age_state}"><b>{age}</b></span>
  <span>policy <b class="mono">{policy}</b></span>
</div>
<p class="reason">{scope}</p>

<div class="cards">
  <div class="card"><div class="n s-warn">{n_critical}</div><div class="l">volumes critical</div></div>
  <div class="card"><div class="n s-warn">{n_warn}</div><div class="l">volumes low</div></div>
  <div class="card"><div class="n s-ok">{free_refetched}</div><div class="l">refetched</div></div>
  <div class="card"><div class="n">{free_rebuilt}</div><div class="l">rebuilt</div></div>
  <div class="card"><div class="n s-warn">{free_destructive}</div><div class="l">destructive</div></div>
  <div class="card"><div class="n s-unknown">{n_unknown}</div><div class="l">could not measure</div></div>
</div>
<p class="reason">The three size cards are what the policy permits removing at
each tier, as measured. They are not space you are about to get back: only the
first costs nothing, and the last does not come back at all.</p>

<h2>Volumes</h2>
<div class="scroll">
<table>
<thead><tr>
  <th scope="col">Volume</th>
  <th scope="col">Total</th>
  <th scope="col">Used</th>
  <th scope="col">Free</th>
  <th scope="col">State</th>
</tr></thead>
<tbody>
{volumes}
</tbody>
</table>
</div>
<div class="legend">
  <span><span class="pill p-ok">ok</span> measured, above both thresholds</span>
  <span><span class="pill p-warn">low</span> / <span class="pill p-warn">critical</span> measured, needs a person — the words carry which</span>
  <span><span class="pill p-unknown">unknown</span> not measured — not the same as nothing wrong</span>
</div>

<h2>Under pressure</h2>
{pressed}

<h2>What to reclaim first</h2>
<p>The cheapest tier only, largest first. Everything here is refetched
automatically by the tool that owns it, so the cost of being wrong is
bandwidth.</p>
{plan}
<p class="reason">Run it with <span class="mono">{remediate}</span>. That is a
dry run and prints what it would remove; nothing is deleted without
<span class="mono">--apply</span>.</p>

<h2>Every target in the policy</h2>
<p>Sorted by size. <b>Safety is the cost of getting the bytes back</b>, not a
guess at risk — and it is what the reclaimer gates on, so a target's tier is the
whole reason it does or does not run by default.</p>
<div class="scroll">
<table>
<thead><tr>
  <th scope="col">Target</th>
  <th scope="col">Safety</th>
  <th scope="col">Measured</th>
  <th scope="col">Largest paths</th>
</tr></thead>
<tbody>
{targets}
</tbody>
</table>
</div>

<h2>What this page could not measure</h2>
{unmeasured}

<footer>
Generated by <span class="mono">ci/disk_dashboard.py</span> from a document
written by <span class="mono">ci/disk_status.py</span>, against
<span class="mono">{policy}</span>. This renderer runs no commands and reads no
filesystem: every figure above is in that document, and a figure that is not in
it is not shown. Correct a number by fixing the generator, not this page.
Refresh with <span class="mono">{refresh}</span>.
</footer>
</main>
"""

TEMPLATE = (
    """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Disk status</title>
<style>{style}</style>
</head>
<body>
"""
    + BODY
    + """</body>
</html>
"""
)

FRAGMENT = "<style>{style}</style>\n" + BODY


def render_markdown(document: dict) -> str:
    """The same document, for a reader that parses rather than looks.

    An agent opening the HTML page is parsing a rendering, and the first thing
    it loses is the distinction the page spends its colours on: `unknown` is a
    span class there and a word here. So every state is stated in words, and
    none is left implied by an empty cell.
    """
    generator = document.get("generator", {})
    reading = document.get("reading", {})
    totals = document.get("totals", {})
    reclaimable = totals.get("reclaimable_bytes") or {}
    lines: list[str] = []
    add = lines.append

    stale_text, _ = staleness(document)

    add("# Disk status")
    add("")
    add(f"- generated: **{document.get('generated_at')}** ({stale_text})")
    add(f"- policy: `{generator.get('policy')}`")
    add(f"- scope: {generator.get('scope')}")
    if reading.get("staleness_budget_hours"):
        add(
            f"- **quote nothing here that is older than "
            f"{reading['staleness_budget_hours']}h.** Refresh: "
            f"`{reading.get('refresh')}`"
        )
    add("")
    add(
        "`unknown` is a value: the target could not be measured, and the reason "
        "is given. It is not zero and not empty."
    )
    add("")
    add(
        f"**Totals** — {totals.get('volumes')} volumes "
        f"({totals.get('volumes_critical')} critical, {totals.get('volumes_warn')} low, "
        f"{totals.get('volumes_unknown')} unreadable); "
        f"{totals.get('targets_measured')} of {totals.get('targets')} targets measured. "
        f"Reclaimable as measured: {size(reclaimable.get('refetched'))} refetched, "
        f"{size(reclaimable.get('rebuilt'))} rebuilt, "
        f"{size(reclaimable.get('destructive'))} destructive."
    )
    add("")

    add("## Volumes")
    add("")
    add("| Volume | Total | Used | Free | Free ratio | State |")
    add("|---|---|---|---|---|---|")
    for volume in document.get("volumes", []):
        reason = unknown_reason(volume.get("usage"))
        if reason is not None:
            add(
                f"| {volume.get('path')} | unknown | unknown | unknown | unknown "
                f"| unknown ({reason}) |"
            )
            continue
        ratio = volume.get("free_ratio")
        add(
            f"| {volume.get('path')} | {size(volume.get('total_bytes'))} "
            f"| {size(volume.get('used_bytes'))} | {size(volume.get('free_bytes'))} "
            f"| {f'{ratio:.1%}' if isinstance(ratio, float) else 'unknown'} "
            f"| {volume.get('severity', 'unknown')} |"
        )
    add("")

    add("## Targets")
    add("")
    add(f"Safety is {generator.get('safety_means', 'unstated in this document')}.")
    add("")
    add("| Target | Safety | Measured | Largest path |")
    add("|---|---|---|---|")
    for target in sorted(
        document.get("targets", []),
        key=lambda t: -((t.get("measured") or {}).get("bytes") or 0),
    ):
        measured = target.get("measured") or {}
        reason = unknown_reason(measured)
        if reason is not None:
            add(
                f"| {target.get('name')} | {target.get('safety')} "
                f"| unknown | unknown ({reason}) |"
            )
            continue
        units = measured.get("units") or []
        biggest = (
            f"{units[0].get('path')} ({size(units[0].get('bytes'))})"
            if units
            else measured.get("note") or "no separate paths"
        )
        add(
            f"| {target.get('name')} | {target.get('safety')} "
            f"| {size(measured.get('bytes'))} | {biggest} |"
        )
    add("")

    add("## What needs a human")
    add("")
    actions = []
    for volume in document.get("volumes", []):
        reason = unknown_reason(volume.get("usage"))
        if reason is not None:
            actions.append(
                f"- **{volume.get('path')}**: could not be measured — {reason}. "
                "A volume nobody could read is not a volume with room on it."
            )
            continue
        if volume.get("severity") in ("warn", "critical"):
            actions.append(
                f"- **{volume.get('path')}** is {volume.get('severity')}: "
                f"{size(volume.get('free_bytes'))} free of "
                f"{size(volume.get('total_bytes'))}. "
                + "; ".join(volume.get("thresholds_fired") or [])
                + f". Start with `{reading.get('remediate', '')}`, which is a dry "
                "run and deletes nothing."
            )
    for target in document.get("targets", []):
        if unknown_reason(target.get("measured")) is not None:
            continue
        unreadable = (target["measured"].get("unreadable") or 0)
        if unreadable:
            actions.append(
                f"- **{target.get('name')}**: {unreadable} paths could not be read, "
                f"so {size(target['measured'].get('bytes'))} is a floor and not a "
                "measurement."
            )
    lines.extend(actions or ["- nothing"])
    add("")

    add("## What this document could not establish")
    add("")
    gaps = [
        f"- **{t.get('name')}**: {unknown_reason(t.get('measured'))}"
        for t in document.get("targets", [])
        if unknown_reason(t.get("measured")) is not None
    ]
    gaps += [
        f"- **{v.get('path')}**: {unknown_reason(v.get('usage'))}"
        for v in document.get("volumes", [])
        if unknown_reason(v.get("usage")) is not None
    ]
    lines.extend(gaps or ["- nothing; every volume and every target was measured"])
    add("")

    for warning in reading.get("do_not") or []:
        add(f"> Do not {warning}.")
    add("")
    add(
        f"Generated by `{generator.get('tool')}`. This view runs no commands and "
        "reads no filesystem — correct a fact by fixing the generator."
    )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    # The agent view is read from stdout as often as from a file, and it carries
    # text this tool did not author -- a command's stderr, a path from somebody's
    # home directory. On a cp1252 console the em dashes in its own prose arrive
    # as replacement characters and anything worse raises.
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8", errors="replace")

    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("document", type=Path, help="the disk status document")
    parser.add_argument("--out", type=Path, help="write here instead of stdout")
    parser.add_argument(
        "--fragment",
        action="store_true",
        help="emit the page without a document shell, for a host that supplies one",
    )
    parser.add_argument(
        "--format",
        choices=("html", "md"),
        default="html",
        help="html for a person, md for an agent. Same document either way.",
    )
    args = parser.parse_args(argv)

    if not args.document.exists():
        sys.exit(
            f"disk_dashboard: no document at {args.document}. Refusing to render "
            "an empty page, which would read as a machine with room on it."
        )
    document = json.loads(args.document.read_text(encoding="utf-8"))
    if document.get("schema") != 1 or "volumes" not in document:
        sys.exit(
            f"disk_dashboard: {args.document} is not a disk status document "
            "(schema 1 with a volumes list)."
        )

    page = (
        render_markdown(document)
        if args.format == "md"
        else render(document, fragment=args.fragment)
    )
    if args.out:
        args.out.write_text(page, encoding="utf-8", newline="\n")
        print(f"wrote {args.out}")
    else:
        sys.stdout.write(page)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
