#!/usr/bin/env python3
"""Emit the loose-ends document: what this org has left open, in one place.

**FIVE DOCUMENTS EACH HOLD PART OF THE ANSWER AND NOBODY READS THEM TOGETHER.**
A thread stalled for two years sits in `status/harness.yaml`. Twenty-seven
records awaiting a human's ratification sit in `status/documents.yaml`. Seventeen
declared blind spots sit in `status/gates.yaml`, one per gate, in the field that
says what it *cannot* see. Each document is correct and each is read for its own
question, so the standing total -- what has this organisation started and not
finished -- is a number nobody has.

This is a **join, not a measurement**. Every fact here is already a fact in a
document this corpus generates; nothing is collected fresh and nothing reaches
the network. That is the same split `ci/harness_status.py` states: a renderer
that can run a command is a second place a rule gets defined. A collector that
can take its own reading is the same error one layer up.

CLAIM AND EVIDENCE ARE SEPARATE, AND ONLY ONE OF THEM IS GENERATED.

  - **Evidence** is what a generator measured, with the document and timestamp
    it came from. This file writes it and rewrites it on every run.
  - **A claim is what a person asserted**, and it is read from
    `registers/loose-end-claims.yaml` -- an input, never an output. A claim
    written into the generated document would be erased by the next run, which
    is the one thing a record of somebody's judgement must never do.

An item nobody has judged has **no claim block at all**. That is different from
one somebody looked at and let go, and rendering them alike is what makes a list
of open questions stop being read.

**AN ADDRESS NAMES THE THING, NOT THE FINDING.** `ci/addresses.py` closes its
`KINDS` set on purpose, and a `loose-end` kind is not in it. Nor should it be: a
loose end is always *about* something the grammar can already name -- a pull
request, a document, a gate's page. So each item addresses its subject with an
existing kind and carries its own `kind` beside it. A view that can resolve an
address can therefore navigate from any loose end to the thing it concerns,
which is the property `project-seed/address-vectors.json` says the round trip
exists for.

UNKNOWN IS A VALUE. A source this tool could not read is written as
`{"unknown": "<reason>"}` and its items are absent rather than empty, because an
absent list reads as "nothing is open" and that is the opposite of what a
missing input means. `handbook/glossary.md` gives the spelling.

WHAT THIS CANNOT DO. Decide whether a loose end matters. It reports what four
documents say is unfinished; which of those is worth anybody's afternoon is a
person's call, and the claims register is where that call is written down.

Usage:
    python ci/loose_ends.py --write loose-ends.json
    python ci/loose_ends.py --check loose-ends.json
"""

from __future__ import annotations

import argparse
import json

import yaml
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

SCHEMA = 1

# The documents this joins. Each is generated by this corpus and committed, so
# the join reaches no network and runs in a fraction of a second.
SOURCES = {
    "harness": "status/harness.yaml",
    "docs": "status/documents.yaml",
    "gates": "status/gates.yaml",
}

CLAIMS = "registers/loose-end-claims.yaml"

# How long an item's evidence is quotable before it should be regenerated. The
# join is only as fresh as its stalest input, and the harness document is the
# one that moves -- so this matches its budget rather than inventing a looser
# one.
STALENESS_BUDGET_HOURS = 24

# What a person may have decided about an item. `open` is not in the set: it is
# the absence of a claim, not a claim of its own, and giving it a spelling would
# invite somebody to write it down and lose the distinction.
DISPOSITIONS = ("carried", "dismissed")


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _unknown(why: str) -> dict[str, str]:
    return {"unknown": why}


def _read_document(root: Path, name: str) -> Any:
    """One source document, or `unknown` with the reason it could not be read.

    The status documents are YAML (`status/*.yaml`); YAML is a superset of
    JSON, so `safe_load` reads either shape without a second code path.
    """
    path = root / name
    if not path.exists():
        return _unknown(f"{name} is not in this corpus; run `uv run qm docs generate`")
    try:
        return yaml.safe_load(path.read_text(encoding="utf-8"))
    except Exception as exc:                       # noqa: BLE001
        return _unknown(f"{name} could not be parsed: {type(exc).__name__}: {exc}")


def _is_unknown(value: Any) -> bool:
    return isinstance(value, dict) and "unknown" in value


# --- the collectors -----------------------------------------------------------
#
# One per kind. Each takes a source document and returns items, and each is
# responsible for saying nothing when the document could not be read -- the
# caller records the reason once, in `sources`.


def stalled_threads(harness: Any) -> list[dict]:
    """Work in flight that has stopped moving.

    `stalled` and `idle_hours` are the harness document's own words; nothing
    here re-derives them. The threshold lives there too, so this cannot drift
    from what the harness dashboard shows.
    """
    found = []
    for repo in harness.get("repositories", []):
        slug = repo.get("slug") or repo.get("name")
        threads = repo.get("threads")
        if _is_unknown(threads) or not threads:
            continue
        for thread in threads:
            if not thread.get("stalled"):
                continue
            pr = thread.get("pr")
            idle = thread.get("idle_hours")
            found.append({
                "kind": "stalled-thread",
                "address": f"{slug}/pr/{pr}" if pr else f"{slug}",
                "title": thread.get("title") or thread.get("name") or "(untitled)",
                "detail": (
                    f"open on {thread.get('base', '?')} at stage "
                    f"{thread.get('stage', '?')}, idle "
                    f"{round(idle):,} hours" if isinstance(idle, (int, float))
                    else f"stage {thread.get('stage', '?')}, idle time unknown"),
                "author": thread.get("author"),
            })
    return found


def over_slot(harness: Any) -> list[dict]:
    """A repository holding more open pull requests than the contract allows.

    The rule and its exemptions are the harness document's; this reports the
    violations it already recorded rather than recounting them.
    """
    found = []
    for repo in harness.get("repositories", []):
        slug = repo.get("slug") or repo.get("name")
        slots = repo.get("slots") or {}
        if _is_unknown(slots):
            continue
        for violation in slots.get("violations") or []:
            found.append({
                "kind": "over-slot",
                "address": str(slug),
                "title": f"{slug} is over its pull-request slot",
                "detail": _violation(violation),
            })
    return found


def _violation(violation: Any) -> str:
    """One slot violation, in a sentence.

    The harness records these as a mapping, and pasting the mapping into a
    detail column puts JSON in front of a person for a fact that is one
    sentence long. Anything shaped unexpectedly falls back to the raw value
    rather than being dropped -- a violation nobody can read is still a
    violation, and silently losing it would be worse than an ugly line.
    """
    if isinstance(violation, str):
        return violation
    if not isinstance(violation, dict):
        return str(violation)
    numbers = violation.get("numbers") or []
    author = violation.get("author") or "somebody"
    base = violation.get("base") or ""
    where = f" against {base}" if base else ""
    if numbers:
        listed = ", ".join(f"#{n}" for n in numbers)
        return (f"{author} holds {len(numbers)} open pull requests{where} "
                f"({listed}); the contract allows one")
    return json.dumps(violation, sort_keys=True)


def waiting_on_a_person(docs: Any) -> list[dict]:
    """Documents whose next step is a human act, and only those.

    `proposed` is drafted and awaiting ratification; `unreviewed` is written
    and nobody has looked. Both are things a person owes the corpus, which is
    what makes them loose ends rather than merely states. `draft`, `standing`,
    `transient` and `generated` are not: those are resting places, and listing
    them would bury the seventy-four that are not.
    """
    owed = {"proposed": "awaiting a human's ratification",
            "unreviewed": "written, and no maintainer has looked at it"}
    found = []
    for document in docs.get("documents", []):
        state = document.get("state")
        if state not in owed:
            continue
        path = document.get("path", "")
        found.append({
            "kind": f"document-{state}",
            "address": f"quaternionmedia/qm/doc/{_slug(path)}",
            "title": path or "(unnamed document)",
            "detail": owed[state] + (f" -- {document['note']}"
                                     if document.get("note") else ""),
        })
    return found


def blind_spots(gates: Any) -> list[dict]:
    """What each gate says it cannot see.

    **DECLARED, NOT DISCOVERED.** Every entry here was written by whoever built
    the gate, in the gate's own `cannot_see` field. That makes this the one
    collector whose items are already somebody's considered judgement -- and it
    is still a loose end, because a declared gap is a gap.
    """
    found = []
    for gate in gates.get("gates", []):
        says = gate.get("cannot_see")
        if not says or _is_unknown(says):
            continue
        found.append({
            "kind": "blind-spot",
            "address": f"quaternionmedia/qm/doc/gate-{gate.get('id', 'unknown')}",
            "title": f"{gate.get('id', '?')} cannot see",
            "detail": says,
        })
    return found


def _slug(path: str) -> str:
    """A document path as an address id: no slashes, no extension."""
    stem = path.rsplit("/", 1)[-1]
    if stem.endswith(".md"):
        stem = stem[:-3]
    return (path.replace("/", "-").replace(".md", "") or stem).strip("-")


# --- claims -------------------------------------------------------------------


def read_claims(root: Path, name: str = CLAIMS) -> Any:
    """What people have decided, keyed `<kind>:<address>`.

    Parsed without PyYAML: the register is a flat mapping of one-line records
    and the corpus's seed scripts run with no dependencies beyond the standard
    library. A key with an unrecognised disposition is reported rather than
    dropped -- a typo that silently voided somebody's decision would be worse
    than the decision being absent.
    """
    path = root / name
    if not path.exists():
        return {}
    claims: dict[str, dict] = {}
    current: str | None = None
    try:
        for raw in path.read_text(encoding="utf-8").splitlines():
            line = raw.split("#", 1)[0].rstrip()
            if not line.strip():
                continue
            if not line.startswith(" ") and line.endswith(":"):
                current = line[:-1].strip().strip('"').strip("'")
                claims[current] = {}
                continue
            if current and ":" in line:
                key, _, value = line.strip().partition(":")
                claims[current][key.strip()] = value.strip().strip('"').strip("'")
    except Exception as exc:                       # noqa: BLE001
        return _unknown(f"{name} could not be read: {type(exc).__name__}: {exc}")
    return claims


# --- the document -------------------------------------------------------------


def _parses(address: str) -> bool:
    """Whether the corpus grammar can resolve this address.

    Imported rather than reimplemented: a second parser is a second grammar,
    and `project-seed/address-vectors.json` exists precisely so there is one.
    A corpus without the module answers `unknown` by returning False, which is
    the conservative reading -- a view told an address parses when it does not
    renders a link that goes nowhere.
    """
    try:
        from ci import addresses
    except Exception:                              # noqa: BLE001
        try:
            import addresses                       # running in place, from ci/
        except Exception:                          # noqa: BLE001
            return False
    try:
        return addresses.parse(address) is not None
    except Exception:                              # noqa: BLE001
        return False


VECTORS = "project-seed/loose-end-vectors.json"


def judge(item: dict, claims: dict) -> dict:
    """How one item reads, given what people have claimed about it.

    **THE WHOLE CONTRACT IS THIS FUNCTION.** `build` uses it and so does the
    vector runner, so a case that passes here is a statement about the document
    a consumer receives and not about a test double. A second implementation of
    the same rule -- one for the generator, one for the checker -- is exactly
    the drift `project-seed/address-vectors.json` was written to stop.
    """
    key = f"{item.get('kind')}:{item.get('address')}"
    claim = claims.get(key) if isinstance(claims, dict) else None
    honoured = bool(claim) and claim.get("disposition") in DISPOSITIONS
    return {
        "key": key,
        "open": not honoured,
        "has_claim": honoured,
        "disposition": claim.get("disposition") if honoured else None,
        "address_parses": _parses(str(item.get("address", ""))),
    }


def run_vectors(root: Path, path: str = VECTORS) -> list[str]:
    """Every case, and what disagreed. Empty means conforming."""
    where = root / path
    if not where.exists():
        return [f"{path} is not there, so nothing was checked -- which is the "
                f"finding, not a pass"]
    cases = json.loads(where.read_text(encoding="utf-8")).get("cases", [])
    if not cases:
        return [f"{path} holds no cases, so this check is vacuous"]

    problems: list[str] = []
    for case in cases:
        given = case.get("given", {})
        got = judge(given.get("item", {}), given.get("claims", {}))
        for field, wanted in case.get("expect", {}).items():
            if got.get(field) != wanted:
                problems.append(
                    f"{case.get('name', '?')}: expected {field}={wanted!r}, "
                    f"got {got.get(field)!r}")
    return problems


def build(root: Path) -> dict:
    """Join every source into one document."""
    harness = _read_document(root, SOURCES["harness"])
    docs = _read_document(root, SOURCES["docs"])
    gates = _read_document(root, SOURCES["gates"])
    claims = read_claims(root)

    sources: dict[str, Any] = {}
    items: list[dict] = []

    for label, document, collectors in (
        ("harness", harness, (stalled_threads, over_slot)),
        ("docs", docs, (waiting_on_a_person,)),
        ("gates", gates, (blind_spots,)),
    ):
        if _is_unknown(document):
            sources[label] = document
            continue
        sources[label] = {
            "document": SOURCES[label],
            "generated_at": document.get("generated_at", _unknown("the source states no time")),
        }
        for collector in collectors:
            items.extend(collector(document))

    # The claim is attached here rather than inside a collector, so every kind
    # gets it on the same terms and no collector can invent one.
    unclaimed = 0
    for item in items:
        key = f"{item['kind']}:{item['address']}"
        item["key"] = key
        read = judge(item, {} if _is_unknown(claims) else claims)
        # **REPORTED, NOT ENFORCED.** An address that does not parse is still a
        # real finding and dropping it would hide one; what it cannot do is
        # link a row to its subject, and a view needs to know that before it
        # renders a dead link.
        item["address_parses"] = read["address_parses"]
        if read["has_claim"]:
            item["claim"] = claims[key]
        else:
            unclaimed += 1

    items.sort(key=lambda one: (one["kind"], one["address"]))

    by_kind: dict[str, int] = {}
    for item in items:
        by_kind[item["kind"]] = by_kind.get(item["kind"], 0) + 1

    return {
        "schema": SCHEMA,
        "generated_at": _now(),
        "generator": {
            "tool": "ci/loose_ends.py",
            "joins": list(SOURCES.values()),
            "reaches_network": False,
            "rule": "an item is open until a person writes a claim about it",
            "claims_source": CLAIMS,
            "claims_are_never_generated": (
                "a claim is what a person asserted. It is read from the "
                "register and never written here, because a claim written "
                "into a generated document is erased by the next run."),
            "dispositions": list(DISPOSITIONS),
            "open_is_the_absence_of_a_claim": (
                "an item nobody has judged carries no claim block. That is a "
                "different fact from one somebody looked at and let go."),
            "addresses": (
                "each item addresses its subject with a kind from "
                "ci/addresses.py, which is closed. There is no loose-end kind: "
                "a loose end is always about something the grammar can name."),
            "sources": sources,
        },
        "reading": {
            "refresh": "python ci/loose_ends.py --write loose-ends.json",
            "staleness_budget_hours": STALENESS_BUDGET_HOURS,
            "as_fresh_as": "its stalest input; each source's own time is in generator.sources",
            "do_not": [
                "do not write a claim into this file -- it is regenerated, and "
                f"the register at {CLAIMS} is where a decision survives",
                "do not read an absent kind as zero: a source that could not "
                "be read is recorded as unknown in generator.sources",
                "do not treat the total as a backlog to burn down. A declared "
                "blind spot is a gap somebody chose and wrote down.",
            ],
        },
        "totals": {
            "loose_ends": len(items),
            "by_kind": by_kind,
            "open": unclaimed,
            "claimed": len(items) - unclaimed,
            "sources_unreadable": sum(1 for v in sources.values() if _is_unknown(v)),
        },
        "loose_ends": items,
    }


def _stable(document: dict) -> str:
    """The document without its timestamp, for comparing two runs."""
    copy = json.loads(json.dumps(document))
    copy.pop("generated_at", None)
    return json.dumps(copy, indent=2, sort_keys=True)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--write", metavar="PATH", help="write the document")
    parser.add_argument("--check", metavar="PATH",
                        help="compare against a committed copy, changing nothing")
    parser.add_argument("--format", choices=("json", "md"), default="json")
    parser.add_argument("--vectors", action="store_true",
                        help="run the conformance vectors and change nothing")
    args = parser.parse_args(argv)

    root = Path.cwd()

    if args.vectors:
        problems = run_vectors(root)
        for line in problems:
            print(line, file=sys.stderr)
        if problems:
            return 1
        print(f"{VECTORS}: every case conforms")
        return 0

    document = build(root)

    if args.check:
        path = root / args.check
        if not path.exists():
            print(f"{args.check} is not there; run --write", file=sys.stderr)
            return 1
        committed = json.loads(path.read_text(encoding="utf-8"))
        if _stable(committed) != _stable(document):
            print(f"{args.check} has drifted from what the sources now say. "
                  f"Run: python ci/loose_ends.py --write {args.check}",
                  file=sys.stderr)
            return 1
        print(f"{args.check} is current")
        return 0

    rendered = (render(document) if args.format == "md"
                else json.dumps(document, indent=2) + "\n")
    if args.write:
        (root / args.write).write_text(rendered, encoding="utf-8")
        print(f"wrote {args.write}: {document['totals']['loose_ends']} loose end(s), "
              f"{document['totals']['open']} open")
        return 0
    print(rendered, end="")
    return 0


def render(document: dict) -> str:
    """The document as prose. ASCII only, as every view here is."""
    totals = document["totals"]
    lines = [
        "# Loose ends",
        "",
        f"{totals['loose_ends']} open question(s) across "
        f"{len(document['generator']['joins'])} document(s): "
        f"{totals['open']} nobody has judged, {totals['claimed']} claimed.",
        "",
    ]
    unreadable = [k for k, v in document["generator"]["sources"].items()
                  if _is_unknown(v)]
    if unreadable:
        lines += [f"**{len(unreadable)} source(s) could not be read**, so this "
                  f"is a floor and not a total: " + ", ".join(unreadable), ""]
    current = None
    for item in document["loose_ends"]:
        if item["kind"] != current:
            current = item["kind"]
            lines += [f"## {current}", ""]
        claim = item.get("claim")
        mark = f"[{claim['disposition']}] " if claim else ""
        lines.append(f"- {mark}`{item['address']}` -- {item['title']}")
        lines.append(f"      {item['detail']}")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    sys.exit(main())
